version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - client
    #build: ./nginx
    image: bestestc09group.azurecr.io/project-bestestc09group_nginx:latest
    restart: always
    ports:
      - "80:80"
      - "8888:8888"

  api:
    #build: ./server
    image: bestestc09group.azurecr.io/project-bestestc09group_api:latest
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:3001"
    environment:
      - MDB_PASSWORD=$MDB_PASSWORD
      - DB_NAME=$DB_NAME
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - REDIRECT_URI=$REDIRECT_URI
      - SESSION_SECRET=$SESSION_SECRET

  client:
    #build: ./client
    image: bestestc09group.azurecr.io/project-bestestc09group_client:latest
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  